{
 "title": "Dual BMS",
 "description": "Dashboard for showing 1 or 2 BMS inputs.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "factory_id",
    "label": "BMS name 1",
    "query": {
     "query": "SHOW TAG VALUES FROM \"BMS\" WITH KEY = \"pack_Naming_of_factory_ID\""
    }
   },
   {
    "name": "factory_id_2",
    "label": "BMS name 2",
    "query": {
     "query": "SHOW TAG VALUES FROM \"BMS\" WITH KEY = \"pack_Naming_of_factory_ID\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Voltage (${factory_id})",
   "type": "gauge",
   "description": "The current voltage of this BMS, Note: a BMS (Battery Management System) is comprised of 1 or more cells.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BMS",
     "query": "SELECT last(\"pack_packV\") FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::tag =~ /^$factory_id$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pack_packV" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Historical Voltage Comparison",
   "type": "timeseries",
   "description": "The two BMS voltages mapped together. Most times they should be identical.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "(${factory_id})",
     "measurement": "BMS",
     "query": "SELECT \"pack_packV\" FROM \"BMS\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pack_packV" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id$/" }
     ]
    },
    {
     "alias": "(${factory_id_2})",
     "measurement": "BMS",
     "query": "SELECT \"pack_packV\" FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::tag =~ /^$factory_id_2$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "pack_packV" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id_2$/" }
     ]
    }
   ]
  },
  {
   "title": "Voltage (${factory_id_2})",
   "type": "gauge",
   "description": "The current voltage of this BMS, Note: a BMS (Battery Management System) is comprised of 1 or more cells.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BMS",
     "query": "SELECT last(\"pack_packV\") FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::field = 'SB-12-1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pack_packV" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id_2$/" }
     ]
    }
   ]
  },
  {
   "title": "Amperage (${factory_id})",
   "type": "gauge",
   "description": "The current amperage of this BMS, Note: a BMS (Battery Management System) is comprised of 1 or more cells.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BMS",
     "query": "SELECT last(\"pack_packV\") FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::field =~ /^$factory_id$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pack_packA" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Historical Amperage Comparison",
   "type": "timeseries",
   "description": "The two BMS amperages mapped together. Most times they should be identical.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "(${factory_id})",
     "measurement": "BMS",
     "query": "SELECT \"pack_packV\" FROM \"BMS\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pack_packA" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id$/" }
     ]
    },
    {
     "alias": "(${factory_id_2})",
     "measurement": "BMS",
     "query": "SELECT \"pack_packV\" FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::tag =~ /^$factory_id_2$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "pack_packA" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id_2$/" }
     ]
    }
   ]
  },
  {
   "title": "Amperage (${factory_id_2})",
   "type": "gauge",
   "description": "The current amperage of this BMS, Note: a BMS (Battery Management System) is comprised of 1 or more cells.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BMS",
     "query": "SELECT last(\"pack_packV\") FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::field =~ /^$factory_id$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pack_packA" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id_2$/" }
     ]
    }
   ]
  },
  {
   "title": "SOC (${factory_id})",
   "type": "gauge",
   "description": "The current SOC of this BMS, Note: a BMS (Battery Management System) is comprised of 1 or more cells.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BMS",
     "query": "SELECT last(\"pack_packV\") FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::field =~ /^$factory_id$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pack_packSOC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Historical SOC Comparison",
   "type": "timeseries",
   "description": "The two BMS SOCs mapped together. Most times they should be identical.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "(${factory_id})",
     "measurement": "BMS",
     "query": "SELECT \"pack_packV\" FROM \"BMS\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pack_packSOC" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id$/" }
     ]
    },
    {
     "alias": "(${factory_id_2})",
     "measurement": "BMS",
     "query": "SELECT \"pack_packV\" FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::tag =~ /^$factory_id_2$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "pack_packSOC" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id_2$/" }
     ]
    }
   ]
  },
  {
   "title": "SOC (${factory_id_2})",
   "type": "gauge",
   "description": "The current SOC of this BMS, Note: a BMS (Battery Management System) is comprised of 1 or more cells.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BMS",
     "query": "SELECT last(\"pack_packV\") FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::field =~ /^$factory_id$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pack_packSOC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id_2$/" }
     ]
    }
   ]
  },
  {
   "title": "Cell Voltages",
   "type": "timeseries",
   "description": "The voltages of the individual cells",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$factory_id (Cell 1)",
     "measurement": "BMS",
     "query": "SELECT \"cells_cell0V\" FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::tag =~ /^$factory_id$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cells_cell0V" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=", "value": "$factory_id" }
     ]
    },
    {
     "alias": "$factory_id (Cell 2)",
     "measurement": "BMS",
     "query": "SELECT \"cells_cell0V\" FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::tag =~ /^$factory_id$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cells_cell1V" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=", "value": "$factory_id" }
     ]
    },
    {
     "alias": "$factory_id (Cell 3)",
     "measurement": "BMS",
     "query": "SELECT \"cells_cell0V\" FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::tag =~ /^$factory_id$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cells_cell2V" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=", "value": "$factory_id" }
     ]
    },
    {
     "alias": "$factory_id (Cell 4)",
     "measurement": "BMS",
     "query": "SELECT \"cells_cell3V\" FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::tag =~ /^$factory_id$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cells_cell3V" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=", "value": "$factory_id" }
     ]
    },
    {
     "alias": "$factory_id_2 (Cell 1)",
     "measurement": "BMS",
     "query": "SELECT \"cells_cell3V\" FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::tag =~ /^$factory_id$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cells_cell0V" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id_2$/" }
     ]
    },
    {
     "alias": "$factory_id_2 (Cell 2)",
     "measurement": "BMS",
     "query": "SELECT \"cells_cell3V\" FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::tag =~ /^$factory_id$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cells_cell1V" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id_2$/" }
     ]
    },
    {
     "alias": "$factory_id_2 (Cell 3)",
     "measurement": "BMS",
     "query": "SELECT \"cells_cell3V\" FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::tag =~ /^$factory_id$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cells_cell2V" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id_2$/" }
     ]
    },
    {
     "alias": "$factory_id_2 (Cell 4)",
     "measurement": "BMS",
     "query": "SELECT \"cells_cell3V\" FROM \"BMS\" WHERE (\"pack_Naming_of_factory_ID\"::tag =~ /^$factory_id$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cells_cell3V" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pack_Naming_of_factory_ID::tag", "operator": "=~", "value": "/^$factory_id_2$/" }
     ]
    }
   ]
  }
 ]
}